### ISSUE TITLE
Broken JSON when undefs are encoded

### ISSUE THREAD

**Issue by zoffixznet** [benkasminbullock/json-create#1] opened 2015-10-19 18:44 UTC
The docs advertise `undef`s to be encoded as `null`s, but currently broken JSON is generated instead:

``` bash
$ perl -MJSON::Create=create_json -wlE 'say create_json $_ for undef, [undef], {foo => undef}'
Use of uninitialized value in say at -e line 1.

[]
{"foo":}
```

**Comment by benkasminbullock** [comment] 2015-10-20 00:53
Thank you for your report. This is fixed via

commit 4a6384e6da0968f93160d4b3a54c6efcf12453ea

If you are interested, details of what happened follow.

Thank you again for your report.

---

The error was here:

https://github.com/benkasminbullock/json-create/commit/4a6384e6da0968f93160d4b3a54c6efcf12453ea#diff-c83f00e3dc9c5499b21409dd7e8ffb5aL114

It was testing the value of the character ("c") before, rather than after, reading it from the master string ("s"). In other words it was making a meaningless test of an uninitialized value to find where the string ended. 

This had not been detected earlier because everything except "null" production was going via another routine, add_str_len, here:

https://github.com/benkasminbullock/json-create/blob/4a6384e6da0968f93160d4b3a54c6efcf12453ea/json-create-perl.c#L120

Also, there were no tests for the documented behaviour, which claimed to produce null with undefined values. (In fact I had not even confirmed this statement at the time of writing it, let alone writtten module tests.)

---

Thanks once more.

**Closed as completed by benkasminbullock** 2015-10-20 00:53 UTC
